### ISSUE TITLE
Indenting YAML file destroys the structure

### ISSUE THREAD

**Issue by schlauergerd** [ahuth/brackets-indentator#13]
I have the following YAML file (with unnecessary white spaces in the line between ```d:``` and ```e:```):
```yaml
a:
    b:
        c: 123
        d: 456
        
    e: "test"
```

When pressing Ctrl+Alt+I for indenting, I get the following result:
```yaml
a:
b:
c: 123
d: 456

e: "test"
```

IMHO this is a different structure than the original one.

Plugin Version: 1.0.3
